### ISSUE TITLE
Not showing thumbnails

### ISSUE THREAD

**Issue by pranko17** [MetaLabs-inc/react-native-vimeo-iframe#50] opened 2023-01-25 11:48 UTC
Video is working, but thumbnails are not showing.

Code: 
```
      <Vimeo
        allowsInlineMediaPlayback={true}
        contentMode={'recommended'}
        params={`transparent=false`}
        style={styles.video}
        videoId={`${vimeoId}`}
      />
```

Libraries:
```
"react-native-vimeo-iframe": "^1.2.1",
"react-native-webview": "^11.26.0",
```

**Comment by damassi** [comment] 2023-01-25 19:35
Just noticed this too and was about to file a ticket here today! When the video first starts initializing in the iframe one can see a thumbnail in the background, but then once it has initialized the area goes blank, and all that remains is a video play button.

**Comment by Marcoo09** [comment] 2023-02-14 04:08
Hi @damassi @pranko17. Thanks for reporting the issue.
I was not able to reproduce the bug yet, is it happening both ios and android? React Native version? 
It will be great if you could share a reproducible example, I'll check it this week.

**Comment by soufianj** [comment] 2023-03-16 16:10
This is happening to me too, on Ios only, react native 0.71.3 weird because it works fine on android...

**Comment by Marcoo09** [comment] 2023-03-19 01:43
Hi @damassi @pranko17 @soufianj
I'm testing this with a few videos, as I show in the attached video, the first video has a thumbnail and it's showing.
https://user-images.githubusercontent.com/18408823/226149076-dcf81ead-2539-47ea-8a0a-6395a7328ddb.mov

If you would like to test on your project, the video is is 513199601. If you can share a reproducible example or a video to test on my end it would be great.

May be related to [this](https://vimeo.zendesk.com/hc/en-us/articles/4409973487117-Fix-Video-Thumbnails-in-Custom-Applications#:~:text=If%20you%20use%20the%20Vimeo,structure%20will%20not%20be%20updated).

**Comment by soufianj** [comment] 2023-03-20 08:55
Hi @Marcoo09 today after a little bit of testing using the video id 513199601 i found out that the problem is only related to iOS 16.2, all the thumbnails do not appear even after trying with different videos, while on iOS 15.0 they all appear without any problem. I used the same exact props:

```
<Vimeo
     videoId={'513199601'}
     params={'api=1&autoplay=0&responsive=1&playsinline=1'}
     handlers={videoCallbacks}
     onLoadStart={onLoadingStart}
     onLoadEnd={onLoaded}
     style={{width: '100%', aspectRatio: 16 / 9}}
     allowsInlineMediaPlayback={true}
     useWebView2={true}
/>
```

I moved the style inline just to make it easier to share.
I also tried removing all the props beside the videoId but it makes no difference.

**Comment by Marcoo09** [comment] 2023-03-20 12:26
Thanks @soufianj! I was testing on IOS 15.2
I'll tackle it this eek.

**Comment by Marcoo09** [comment] 2023-03-25 21:46
Hi guys, I was reading the documentation and trying different workarounds without success.
It looks like an issue on the [player sdk](https://github.com/vimeo/player.js). There are a couple of issue on this repo talking about this same problem, I'll keep and eye on these issues and as soon as there is a solution I'll fix it.

**Comment by Marcoo09** [comment] 2023-09-11 14:39
Closing this bug as it's working in iOS 17 and on real devices in iOS 16.

**Closed by Marcoo09** 2023-09-11 14:39 UTC
Labels: bug
